version: '3'
services:
  php:
    build: ./php
    container_name: docker_project_php
    tty: true
    volumes:
      - ./www:/var/www
  nginx:
    image: nginx:latest
    container_name: docker_project_nginx
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  mysql:
    image: mysql
    container_name: docker_project_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
